CREATE TABLE national_holidays (
    holiday_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    holiday_name VARCHAR2(255) NOT NULL,
    holiday_date DATE NOT NULL,
    holiday_year NUMBER(4) NOT NULL,
    holiday_type VARCHAR2(100),
    state VARCHAR2(255),
    is_official NUMBER(1) DEFAULT 0 NOT NULL,
    public_holiday NUMBER(1) DEFAULT 0 NOT NULL
);

--TRUNCATE TABLE national_holidays;

--DROP TABLE national_holidays PURGE;

--ALTER TABLE national_holidays READ ONLY;

--ALTER TABLE national_holidays READ WRITE;


